// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Food struct {
	ID            int32
	Lastmodified  pgtype.Timestamp
	Name          string
	Servings      []int32
	Servingsizes  []string
	Calories      float64
	Carbohydrates float64
	Protein       float64
	Fat           float64
	Calcium       float64
	Potassium     float64
	Iron          float64
}
