// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type Food struct {
	ID           int32
	Lastmodified time.Time
	Name         string
	Servings     []int32
	Servingsizes []string
	Calories     float64
	Carbohydrate float64
	Protein      float64
	Fat          float64
	Calcium      float64
	Potassium    float64
	Iron         float64
}

type User struct {
	ID           int32
	Lastmodified time.Time
	Email        string
	Password     string
}
