// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Exercise struct {
	Lastmodified pgtype.Int8
	Deleted      bool
	ID           int32
	Userid       int32
	Workoutid    int32
	Exercisetype string
	Name         string
	Weight       int32
	Reps         []int32
	Duration     float64
}

type Food struct {
	Lastmodified        pgtype.Int8
	ID                  int32
	Userid              int32
	Name                string
	Defaultservingindex int32
	Servingsizes        []float64
	Servingunits        []string
	Calories            float64
	Carbohydrate        float64
	Protein             float64
	Fat                 float64
	Calcium             float64
	Potassium           float64
	Iron                float64
}

type Meal struct {
	Lastmodified pgtype.Int8
	Deleted      bool
	ID           int32
	Userid       int32
	Foodid       int32
	Date         int64
	Mealtag      string
	Servings     float64
	Unit         string
}

type Record struct {
	Lastmodified pgtype.Int8
	Deleted      bool
	Userid       int32
	Recordtype   string
	Date         int64
	Value        float64
}

type Setting struct {
	Lastmodified pgtype.Int8
	ID           int32
	Userid       int32
	Mealtags     []string
	Macrotargets []byte
	Useimperial  bool
	Trackperiod  bool
}

type User struct {
	Lastmodified pgtype.Int8
	ID           int32
	Email        string
	Password     string
}

type Workout struct {
	Lastmodified pgtype.Int8
	Deleted      bool
	ID           int32
	Userid       int32
	Name         string
	Date         int64
	Istemplate   bool
	Notes        string
}
