// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExercise = `-- name: CreateExercise :one
insert into exercises (userID, workoutID, name, weight, reps)
values ($1, $2, $3, $4, $5) returning id
`

type CreateExerciseParams struct {
	Userid    int32
	Workoutid int32
	Name      string
	Weight    int32
	Reps      []int32
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (int32, error) {
	row := q.db.QueryRow(ctx, createExercise,
		arg.Userid,
		arg.Workoutid,
		arg.Name,
		arg.Weight,
		arg.Reps,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createFood = `-- name: CreateFood :one
insert into foods
(userID, name, servingSizes, servingUnits, defaultServingIndex,
calories, carbohydrate, protein, fat, calcium, potassium, iron)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
returning id
`

type CreateFoodParams struct {
	Userid              int32
	Name                string
	Servingsizes        []int32
	Servingunits        []string
	Defaultservingindex int32
	Calories            float64
	Carbohydrate        float64
	Protein             float64
	Fat                 float64
	Calcium             float64
	Potassium           float64
	Iron                float64
}

func (q *Queries) CreateFood(ctx context.Context, arg CreateFoodParams) (int32, error) {
	row := q.db.QueryRow(ctx, createFood,
		arg.Userid,
		arg.Name,
		arg.Servingsizes,
		arg.Servingunits,
		arg.Defaultservingindex,
		arg.Calories,
		arg.Carbohydrate,
		arg.Protein,
		arg.Fat,
		arg.Calcium,
		arg.Potassium,
		arg.Iron,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createMeal = `-- name: CreateMeal :one
insert into meals
(userID, foodID, date, mealTag, servings, unit)
values ($1, $2, $3, $4, $5, $6) returning id
`

type CreateMealParams struct {
	Userid   int32
	Foodid   int32
	Date     int64
	Mealtag  string
	Servings int32
	Unit     string
}

func (q *Queries) CreateMeal(ctx context.Context, arg CreateMealParams) (int32, error) {
	row := q.db.QueryRow(ctx, createMeal,
		arg.Userid,
		arg.Foodid,
		arg.Date,
		arg.Mealtag,
		arg.Servings,
		arg.Unit,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :one
insert into users (email, password) values ($1, $2) returning id
`

type CreateUserParams struct {
	Email    string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Password)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createWorkout = `-- name: CreateWorkout :one
insert into workouts (userID, name, notes, date, isTemplate)
values ($1, $2, $3, $4, $5) returning id
`

type CreateWorkoutParams struct {
	Userid     int32
	Name       string
	Notes      string
	Date       int64
	Istemplate bool
}

func (q *Queries) CreateWorkout(ctx context.Context, arg CreateWorkoutParams) (int32, error) {
	row := q.db.QueryRow(ctx, createWorkout,
		arg.Userid,
		arg.Name,
		arg.Notes,
		arg.Date,
		arg.Istemplate,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteExercise = `-- name: DeleteExercise :exec
update exercises set deleted = true, lastModified = $1 where workoutID = $2 and userID = $3
`

type DeleteExerciseParams struct {
	Lastmodified pgtype.Int8
	Workoutid    int32
	Userid       int32
}

func (q *Queries) DeleteExercise(ctx context.Context, arg DeleteExerciseParams) error {
	_, err := q.db.Exec(ctx, deleteExercise, arg.Lastmodified, arg.Workoutid, arg.Userid)
	return err
}

const deleteExercises = `-- name: DeleteExercises :exec
delete from exercises where userID = $1
`

func (q *Queries) DeleteExercises(ctx context.Context, userid int32) error {
	_, err := q.db.Exec(ctx, deleteExercises, userid)
	return err
}

const deleteFoods = `-- name: DeleteFoods :exec
delete from foods where userID = $1
`

func (q *Queries) DeleteFoods(ctx context.Context, userid int32) error {
	_, err := q.db.Exec(ctx, deleteFoods, userid)
	return err
}

const deleteMeal = `-- name: DeleteMeal :exec
update meals set deleted = true, lastModified = $1
where userID = $2 and id = $3
`

type DeleteMealParams struct {
	Lastmodified pgtype.Int8
	Userid       int32
	ID           int32
}

func (q *Queries) DeleteMeal(ctx context.Context, arg DeleteMealParams) error {
	_, err := q.db.Exec(ctx, deleteMeal, arg.Lastmodified, arg.Userid, arg.ID)
	return err
}

const deleteMeals = `-- name: DeleteMeals :exec
delete from meals where userID = $1
`

func (q *Queries) DeleteMeals(ctx context.Context, userid int32) error {
	_, err := q.db.Exec(ctx, deleteMeals, userid)
	return err
}

const deleteRecord = `-- name: DeleteRecord :exec
update records set deleted = true, lastModified = $1 where userID = $2 and date = $3
`

type DeleteRecordParams struct {
	Lastmodified pgtype.Int8
	Userid       int32
	Date         int64
}

func (q *Queries) DeleteRecord(ctx context.Context, arg DeleteRecordParams) error {
	_, err := q.db.Exec(ctx, deleteRecord, arg.Lastmodified, arg.Userid, arg.Date)
	return err
}

const deleteRecords = `-- name: DeleteRecords :exec
delete from records where userID = $1
`

func (q *Queries) DeleteRecords(ctx context.Context, userid int32) error {
	_, err := q.db.Exec(ctx, deleteRecords, userid)
	return err
}

const deleteSettings = `-- name: DeleteSettings :exec
delete from settings where userID = $1
`

func (q *Queries) DeleteSettings(ctx context.Context, userid int32) error {
	_, err := q.db.Exec(ctx, deleteSettings, userid)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
delete from users where id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const deleteWorkout = `-- name: DeleteWorkout :exec
update workouts set deleted = true, lastModified = $1
where userID = $2 and id = $3
`

type DeleteWorkoutParams struct {
	Lastmodified pgtype.Int8
	Userid       int32
	ID           int32
}

func (q *Queries) DeleteWorkout(ctx context.Context, arg DeleteWorkoutParams) error {
	_, err := q.db.Exec(ctx, deleteWorkout, arg.Lastmodified, arg.Userid, arg.ID)
	return err
}

const deleteWorkouts = `-- name: DeleteWorkouts :exec
delete from workouts where userID = $1
`

func (q *Queries) DeleteWorkouts(ctx context.Context, userid int32) error {
	_, err := q.db.Exec(ctx, deleteWorkouts, userid)
	return err
}

const getExercises = `-- name: GetExercises :many
select lastmodified, deleted, id, userid, workoutid, name, weight, reps from exercises where userID = $1 and workoutID = $2
`

type GetExercisesParams struct {
	Userid    int32
	Workoutid int32
}

func (q *Queries) GetExercises(ctx context.Context, arg GetExercisesParams) ([]Exercise, error) {
	rows, err := q.db.Query(ctx, getExercises, arg.Userid, arg.Workoutid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.Lastmodified,
			&i.Deleted,
			&i.ID,
			&i.Userid,
			&i.Workoutid,
			&i.Name,
			&i.Weight,
			&i.Reps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFoodByID = `-- name: GetFoodByID :one
select lastmodified, id, userid, name, defaultservingindex, servingsizes, servingunits, calories, carbohydrate, protein, fat, calcium, potassium, iron from foods where id = $1
`

func (q *Queries) GetFoodByID(ctx context.Context, id int32) (Food, error) {
	row := q.db.QueryRow(ctx, getFoodByID, id)
	var i Food
	err := row.Scan(
		&i.Lastmodified,
		&i.ID,
		&i.Userid,
		&i.Name,
		&i.Defaultservingindex,
		&i.Servingsizes,
		&i.Servingunits,
		&i.Calories,
		&i.Carbohydrate,
		&i.Protein,
		&i.Fat,
		&i.Calcium,
		&i.Potassium,
		&i.Iron,
	)
	return i, err
}

const getMealsForDay = `-- name: GetMealsForDay :many
select lastmodified, deleted, id, userid, foodid, date, mealtag, servings, unit from meals where date = $1 and userID = $2 and deleted = false
`

type GetMealsForDayParams struct {
	Date   int64
	Userid int32
}

func (q *Queries) GetMealsForDay(ctx context.Context, arg GetMealsForDayParams) ([]Meal, error) {
	rows, err := q.db.Query(ctx, getMealsForDay, arg.Date, arg.Userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meal
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.Lastmodified,
			&i.Deleted,
			&i.ID,
			&i.Userid,
			&i.Foodid,
			&i.Date,
			&i.Mealtag,
			&i.Servings,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpdatedMeals = `-- name: GetUpdatedMeals :many
select lastmodified, deleted, id, userid, foodid, date, mealtag, servings, unit from meals where userID = $1 and lastModified >= $2
`

type GetUpdatedMealsParams struct {
	Userid       int32
	Lastmodified pgtype.Int8
}

func (q *Queries) GetUpdatedMeals(ctx context.Context, arg GetUpdatedMealsParams) ([]Meal, error) {
	rows, err := q.db.Query(ctx, getUpdatedMeals, arg.Userid, arg.Lastmodified)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meal
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.Lastmodified,
			&i.Deleted,
			&i.ID,
			&i.Userid,
			&i.Foodid,
			&i.Date,
			&i.Mealtag,
			&i.Servings,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpdatedRecords = `-- name: GetUpdatedRecords :many
select lastmodified, deleted, userid, recordtype, date, value from records where userID = $1 and lastModified >= $2
`

type GetUpdatedRecordsParams struct {
	Userid       int32
	Lastmodified pgtype.Int8
}

func (q *Queries) GetUpdatedRecords(ctx context.Context, arg GetUpdatedRecordsParams) ([]Record, error) {
	rows, err := q.db.Query(ctx, getUpdatedRecords, arg.Userid, arg.Lastmodified)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Record
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.Lastmodified,
			&i.Deleted,
			&i.Userid,
			&i.Recordtype,
			&i.Date,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpdatedWorkouts = `-- name: GetUpdatedWorkouts :many
select lastmodified, deleted, id, userid, name, date, istemplate, notes from workouts where userID = $1 and lastModified = $2
`

type GetUpdatedWorkoutsParams struct {
	Userid       int32
	Lastmodified pgtype.Int8
}

func (q *Queries) GetUpdatedWorkouts(ctx context.Context, arg GetUpdatedWorkoutsParams) ([]Workout, error) {
	rows, err := q.db.Query(ctx, getUpdatedWorkouts, arg.Userid, arg.Lastmodified)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workout
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.Lastmodified,
			&i.Deleted,
			&i.ID,
			&i.Userid,
			&i.Name,
			&i.Date,
			&i.Istemplate,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
select id, email, Password from users where email = $1 or id = $2
`

type GetUserParams struct {
	Email string
	ID    int32
}

type GetUserRow struct {
	ID       int32
	Email    string
	Password string
}

func (q *Queries) GetUser(ctx context.Context, arg GetUserParams) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, arg.Email, arg.ID)
	var i GetUserRow
	err := row.Scan(&i.ID, &i.Email, &i.Password)
	return i, err
}

const getUserSettings = `-- name: GetUserSettings :one
select lastmodified, id, userid, mealtags, macrotargets, useimperial, trackperiod from settings where userID = $1
`

func (q *Queries) GetUserSettings(ctx context.Context, userid int32) (Setting, error) {
	row := q.db.QueryRow(ctx, getUserSettings, userid)
	var i Setting
	err := row.Scan(
		&i.Lastmodified,
		&i.ID,
		&i.Userid,
		&i.Mealtags,
		&i.Macrotargets,
		&i.Useimperial,
		&i.Trackperiod,
	)
	return i, err
}

const searchFoods = `-- name: SearchFoods :many
select lastmodified, id, userid, name, defaultservingindex, servingsizes, servingunits, calories, carbohydrate, protein, fat, calcium, potassium, iron from foods
where to_tsvector(name) @@ websearch_to_tsquery($1) limit 100
`

func (q *Queries) SearchFoods(ctx context.Context, websearchToTsquery string) ([]Food, error) {
	rows, err := q.db.Query(ctx, searchFoods, websearchToTsquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Food
	for rows.Next() {
		var i Food
		if err := rows.Scan(
			&i.Lastmodified,
			&i.ID,
			&i.Userid,
			&i.Name,
			&i.Defaultservingindex,
			&i.Servingsizes,
			&i.Servingunits,
			&i.Calories,
			&i.Carbohydrate,
			&i.Protein,
			&i.Fat,
			&i.Calcium,
			&i.Potassium,
			&i.Iron,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUserFoods = `-- name: SearchUserFoods :many
select lastmodified, id, userid, name, defaultservingindex, servingsizes, servingunits, calories, carbohydrate, protein, fat, calcium, potassium, iron from foods
where to_tsvector(name) @@ websearch_to_tsquery($1) and userID = $2 limit 100
`

type SearchUserFoodsParams struct {
	WebsearchToTsquery string
	Userid             int32
}

func (q *Queries) SearchUserFoods(ctx context.Context, arg SearchUserFoodsParams) ([]Food, error) {
	rows, err := q.db.Query(ctx, searchUserFoods, arg.WebsearchToTsquery, arg.Userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Food
	for rows.Next() {
		var i Food
		if err := rows.Scan(
			&i.Lastmodified,
			&i.ID,
			&i.Userid,
			&i.Name,
			&i.Defaultservingindex,
			&i.Servingsizes,
			&i.Servingunits,
			&i.Calories,
			&i.Carbohydrate,
			&i.Protein,
			&i.Fat,
			&i.Calcium,
			&i.Potassium,
			&i.Iron,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserSettings = `-- name: SetUserSettings :exec
insert into settings
(userID, mealTags, macroTargets, useImperial, trackPeriod)
values ($1, $2, $3, $4, $5)
on conflict (userID) do update
set mealTags = excluded.mealTags,
    macroTargets = excluded.macroTargets,
    useImperial = excluded.useImperial,
    trackPeriod = excluded.trackPeriod
`

type SetUserSettingsParams struct {
	Userid       int32
	Mealtags     []string
	Macrotargets []byte
	Useimperial  bool
	Trackperiod  bool
}

func (q *Queries) SetUserSettings(ctx context.Context, arg SetUserSettingsParams) error {
	_, err := q.db.Exec(ctx, setUserSettings,
		arg.Userid,
		arg.Mealtags,
		arg.Macrotargets,
		arg.Useimperial,
		arg.Trackperiod,
	)
	return err
}

const setWeight = `-- name: SetWeight :exec
insert into records (userID, recordType, date, value) values ($1, 'weight', $2, $3)
`

type SetWeightParams struct {
	Userid int32
	Date   int64
	Value  int32
}

func (q *Queries) SetWeight(ctx context.Context, arg SetWeightParams) error {
	_, err := q.db.Exec(ctx, setWeight, arg.Userid, arg.Date, arg.Value)
	return err
}

const togglePeriodDate = `-- name: TogglePeriodDate :exec
insert into records (userID, recordType, date, value) values ($1, 'period', $2, $3)
on conflict (userID, recordType, date) do update
set value = 1 - excluded.value, lastModified = $4
`

type TogglePeriodDateParams struct {
	Userid       int32
	Date         int64
	Value        int32
	Lastmodified pgtype.Int8
}

// (toggles the value column between 0/1)
func (q *Queries) TogglePeriodDate(ctx context.Context, arg TogglePeriodDateParams) error {
	_, err := q.db.Exec(ctx, togglePeriodDate,
		arg.Userid,
		arg.Date,
		arg.Value,
		arg.Lastmodified,
	)
	return err
}

const updateMeal = `-- name: UpdateMeal :exec
update meals
set lastModified = $1, mealTag = $2, servings = $3, unit = $4
where ID = $5
`

type UpdateMealParams struct {
	Lastmodified pgtype.Int8
	Mealtag      string
	Servings     int32
	Unit         string
	ID           int32
}

func (q *Queries) UpdateMeal(ctx context.Context, arg UpdateMealParams) error {
	_, err := q.db.Exec(ctx, updateMeal,
		arg.Lastmodified,
		arg.Mealtag,
		arg.Servings,
		arg.Unit,
		arg.ID,
	)
	return err
}

const userExists = `-- name: UserExists :one
select exists(select 1 from users where id = $1)
`

func (q *Queries) UserExists(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
