// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFood = `-- name: CreateFood :exec
insert into Foods
(LastModified, Name, Servings, ServingSizes, Calories,
Carbohydrates, Protein, Fat, Calcium, Potassium, Iron)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
returning id
`

type CreateFoodParams struct {
	Lastmodified  pgtype.Timestamp
	Name          string
	Servings      []int32
	Servingsizes  []string
	Calories      float64
	Carbohydrates float64
	Protein       float64
	Fat           float64
	Calcium       float64
	Potassium     float64
	Iron          float64
}

func (q *Queries) CreateFood(ctx context.Context, arg CreateFoodParams) error {
	_, err := q.db.Exec(ctx, createFood,
		arg.Lastmodified,
		arg.Name,
		arg.Servings,
		arg.Servingsizes,
		arg.Calories,
		arg.Carbohydrates,
		arg.Protein,
		arg.Fat,
		arg.Calcium,
		arg.Potassium,
		arg.Iron,
	)
	return err
}

const findByID = `-- name: FindByID :one
select id, lastmodified, name, servings, servingsizes, calories, carbohydrates, protein, fat, calcium, potassium, iron from Foods where ID = $1
`

func (q *Queries) FindByID(ctx context.Context, id int32) (Food, error) {
	row := q.db.QueryRow(ctx, findByID, id)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.Lastmodified,
		&i.Name,
		&i.Servings,
		&i.Servingsizes,
		&i.Calories,
		&i.Carbohydrates,
		&i.Protein,
		&i.Fat,
		&i.Calcium,
		&i.Potassium,
		&i.Iron,
	)
	return i, err
}
